Algoritmo "Subistiuir valores"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/09/2017
Var
 A,B,C : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite o primeiro valor=")
 leia(A)
 escreva("digite o segundo valor=")
 leia(B)
 C<-A
 A<-B
 B<-C
 escreval("primeiro valor=",A)
 escreval("valor segundo valor=",B)

Fimalgoritmo