Algoritmo "semnome"
// Logica de programação 
// Julio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/09/2017
Var
area,base,altura:real
Inicio
escreva("escreva a base do trialgulo = ")
leia(base)
escreva("escreva a altura do triangulo = ")
leia(altura)
area<-(base*altura)/2
escreva("a area do triangulo é = ",area )
Fimalgoritmo