Algoritmo "semnome"

Var
n1,n2:real
comparacao: caracter

Inicio
Escreva("Digite um numero : ")
leia(n1)
Escreva("Digite um numero : ")
leia(n2)

se n1 = n2 entao
   escreva("Numeros iguais")
senao
     se n1 > n2 entao
        escreva("Numero 1 é maior")
     senao
          se n2 > n1 entao
             escreva("Numero 2 é maior")
          fimse
     fimse
fimse


fimescolha

fimescolha
Fimalgoritmo