Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2017
Var
// Seção de Declarações das variáveis 
n1,dobro:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite um numero : ")
 leia(n1)
 dobro:=(n1*2)
 escreval("o dobro de ",n1," é = ",dobro)

Fimalgoritmo