Algoritmo "semnome"
// Logica de programação 
// Julio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/09/2017
Var
 num,pre,prem:real

Inicio
   escreva ("custo da maça é 1,30 a partir de 12 é 1,00 ")
   leia (num)
    pre <-(num*1.30)
    prem <- (num*1)
   escreval("voce comprou " ,num )
   escreval("custo se comprar menos de 12 ",pre)
   escreval("custo se comprar mais de 11",prem)

Fimalgoritmo