Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/10/2017
Var
// Seção de Declarações das variáveis 
A,M,D:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("digite o ano,o mês e o dia ")
 leia(A,M,D)
 limpatela
 escreval(D,"/",M,"/",A)
      -
Fimalgoritmo