Algoritmo "semnome"

Var
 letra,ler:caracter
Inicio
Escreval("Digite uma letra do alfabeto para saber se é vogal ou consoante : ")
leia(letra)
escolha letra
caso "a"
escreva("Vogal")
ler<-"a"
caso "e"
escreva("Vogal")
ler<-"e"
caso "i"
escreva("Vogal")
ler<-"i"
caso "o"
escreva("Vogal")
ler<-"o"
caso "u"
escreva("Vogal")
ler<-"u"
fimescolha

se letra <> ler entao
Escreva("consoante")
fimse


Fimalgoritmo