Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/10/2017
Var
// Seção de Declarações das variáveis 
n:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite um numero ")
 leia(n)
 se n>0 entao
 escreva (n," é positivo")
 senao
 escreva(n," é negativo")
 fimse

Fimalgoritmo