Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/10/2017
Var
// Seção de Declarações das variáveis
sal:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

 escreva("num")
 leia(sal)
 
se ( sal <=10 ) entao

escreval("menor que 10")

senao
escreval("maior que 10")

fimse

Fimalgoritmo
