Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2017
Var
// Seção de Declarações das variáveis 
cont,val:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont<-20
enquanto cont<=40 faca
val<-cont+val
cont<-cont+1

fimenquanto
 cont<-cont-20
 escreval("Quantidade ",cont)
 escreva(val)

Fimalgoritmo