Algoritmo "semnome"
//7)Construa um programa para apresentar o total da soma obtida da leituras
//dos números inteiros. Entre 8 e 108
Var
num,cont,media:real

Inicio
cont<-8
enquanto cont<=108 faca
num<-cont+num
cont<-cont+1

Fimenquanto
cont<-cont-8
media<-(num/cont)
Escreval("A soma dos numeros de 8 a 108 = ",num)
escreval("A media dos numeros de 8 a 108 = ",media)
Escreva("O contador é = ",cont)


Fimalgoritmo