Algoritmo "semnome"
//9) FAÇA UM ALGORITMO QUE CALCULE A
//ÁREA DE UM TRIÂNGULO QUALQUER, CONSIDERANDO A FÓRMULA
//AREA <-(BASE*ALTURA)/2
//UTILIZE AS VARIÁVEIS AREA, BASE E ALTURA E OS
//OPERADORES ARITMÉTICOS DE MULTIPLICAÇÃO E DIVISÃO.
Var
base,altu,area:real
Inicio
escreva("Digite a base do triangulo : ")
leia(base)
escreva("Digite a altura do triangulo : ")
leia(altu)
area<-(base*altu)/2
escreva("A area do triangulo é : ",area)



Fimalgoritmo