Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2017
Var
// Seção de Declarações das variáveis 
cont,num,re:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont<-6

enquanto cont>1 faca
escreva("digite um numero : ")
leia(num)
  re<-num*3
  
  escreval(num,"X 3 = ",re)
  cont<-cont-1
  fimenquanto

Fimalgoritmo