Algoritmo "semnome"
Var
num,cont,nun,media:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 cont<-0
 enquanto cont<=9 faca
  escreva("digite um numero : ")
  leia(num)
  nun<-nun+num
  cont<-cont+1
 fimenquanto
 media<-nun /10
 escreval("A soma dos numeros lidos é de : ",nun)
 escreval("A quantidade de numeros lidos é de : ",cont)
 escreval("A media dos numeros lidos é : ",media)
Fimalgoritmo