Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2017
Var
// Seção de Declarações das variáveis
cont,num,re:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 cont<-1
 enquanto cont<=4 faca
 escreva("Digite um numero : ")
 leia(num)
 re<-re+num*2
 escreval(re)

 cont<-cont+1
fimenquanto
 escreval("O resultado é = ",re)
Fimalgoritmo