Algoritmo "semnome"
Var
n1,maior,menor,soma:real
x:inteiro

Inicio
repita
repita
escreva("Digite um numero : ")
leia(n1)

se n1 < 0  entao
Escreval("Os valores negativos ou iguais a zero não estarão nos calculos")
senao
x<-2
soma<-soma+n1
fimse


ate x=2
se n1 > maior entao
maior<-n1
senao
se n1  <> 0 entao
menor<-n1
fimse
fimse
escreva

ate n1 =0
Escreval()
escreval("A soma : ",soma)
Escreval("O maior valor : ",maior)
Escreval("O menor valor : ",menor)

Fimalgoritmo