Algoritmo "semnome"
Var
v:vetor[1..5]de real
i:inteiro
nome:caracter

Inicio
para i de 1 ate 5 faca
Escreva("Digite os nomes : ")
leia(v[i])
fimpara
Escreva("Digite o nome que quer procurar : ")
leia(nome)

se nome = v[1] entao
Escreva ("Achei")
fimse

se nome = v[2] entao
Escreva ("Achei")
fimse

se nome = v[3] entao
Escreva ("Achei")
fimse

se nome = v[4] entao
Escreva ("Achei")
fimse

se nome = v[5] entao
Escreva ("Achei")
fimse

Fimalgoritmo
