Algoritmo "semnome"
//4)

Var
sal,sab,comi,val,num,valt,cont:real

Inicio
cont<-1
enquanto cont<=3 faca
limpatela
Escreval("Funcionario : ",cont)
escreva("Digite o salario fixo : ")
leia(sab)
Escreva("Digite quantos carros o vendedor",cont," vendeu : ")
leia(num)
Escreva("Digite o valor dos carros : ")
leia(val)
valt<-sab+((num*val)*5)/100

escreval("O salario final é de : ",valt)
leia(sal)

cont<-cont+1
fimenquanto



Fimalgoritmo