Algoritmo "semnome"
//3) ESCREVA UM PROGRAMA PARA CALCULAR A SOMA ENTRE TODOS OS NÚMEROS COMPREENDIDOS
//ENTRE DOIS NÚMEROS LIDOS DO TECLADO. (EX.: 8...12 = 50)

Var
cont,cont1,soma:real

Inicio
escreva("Digite o numero inicial : ")
leia(cont)
escreva("Digite o numero final : ")
leia(cont1)
enquanto cont<=cont1 faca
soma<-soma+cont
cont<-cont+1
fimenquanto
Escreva("A soma total é = ",soma)


Fimalgoritmo